// This file defines your DVD/media library data.
// It is generated by the DVD CRC64 Hash Lookup tool.
// You can upload this file to your NeoCities site and link it in your HTML
// to pre-load your library.

const initialDVDLibraryData = [
  // Example entry (your actual data will be here after saving)
  // {
  //   "hash": "A1B2C3D4E5F67890",
  //   "title": "Inception",
  //   "year": "2010",
  //   "genre": "Action, Adventure, Sci-Fi",
  //   "plot": "A thief who steals corporate secrets through the use of dream-sharing technology...",
  //   "director": "Christopher Nolan",
  //   "poster": "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg"
  // }
];
